#!/usr/bin/env bash
# install.sh — install the Context Layer tooling (the real MitchForest
# context-layer coordinator/capture/synthesis agents + context-layer/add-rule
# skills) into a target repo's .claude/, so the layer is generated by the SAME
# tooling every repo received during the initial rollout — and so the tooling is
# committed as part of the docs PR (self-maintaining).
#
# Usage: install.sh <target_repo_dir>
set -euo pipefail

TARGET="${1:?usage: install.sh <target_repo_dir>}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"   # .../skills/context-layer/tooling

mkdir -p "$TARGET/.claude/agents" "$TARGET/.claude/skills" "$TARGET/.context-layer"

cp "$HERE/agents/context-layer-coordinator.md" \
   "$HERE/agents/context-layer-capture.md" \
   "$HERE/agents/context-layer-synthesis.md" \
   "$TARGET/.claude/agents/"
cp "$HERE/skills/context-layer.md" \
   "$HERE/skills/add-rule.md" \
   "$TARGET/.claude/skills/"

# CodeGraph verb wrapper — agents call `bash .claude/cg.sh <verb>` for structural facts.
cp "$HERE/cg.sh" "$TARGET/.claude/cg.sh"
chmod +x "$TARGET/.claude/cg.sh"

# manifest scaffold (agents create/refresh it on build); keep it out of git
if [ ! -f "$TARGET/.context-layer/manifest.json" ]; then
  printf '%s\n' '{' '  "version": 1,' '  "systems": []' '}' > "$TARGET/.context-layer/manifest.json"
fi
touch "$TARGET/.gitignore"
grep -q '^\.context-layer' "$TARGET/.gitignore" || echo '.context-layer/' >> "$TARGET/.gitignore"
grep -q '^\.code-graph'    "$TARGET/.gitignore" || echo '.code-graph/'    >> "$TARGET/.gitignore"

echo "installed context-layer tooling into $TARGET/.claude/ (agents: coordinator, capture, synthesis; skills: context-layer, add-rule; cg.sh)"
